CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    is_admin INTEGER NOT NULL,
    crumbles VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);